### ISSUE TITLE
Non-recoverable error on launch

### ISSUE THREAD

**Issue by TheAsKo** [Sopel97/railway_signalling_overseer#1]
Mod list: {big ones K2+SE}
[mod-list.zip](https://github.com/Sopel97/railway_signalling_overseer/files/8911225/mod-list.zip)

First save: {file was too big to upload on github}
https://drive.google.com/file/d/1eyUhUnJWvyoELBNjYKQ-s0_fZ1OVQ6os/view?usp=sharing 
 
Error message: 
![image](https://user-images.githubusercontent.com/107570375/173875950-a25aa30e-8f2e-4c3a-92a0-afaa17937866.png)

Second save: {same mods}
[FILIP MOD 002.zip](https://github.com/Sopel97/railway_signalling_overseer/files/8911257/FILIP.MOD.002.zip)

Error message:
![image](https://user-images.githubusercontent.com/107570375/173876126-6d510b6f-dab7-4090-be38-641d270fc72b.png)

Error is shown on both saves seconds after loading of map , only new mod that was added to modpack during playthrough , nothing removed ... 

Edit: Only thing i can think of that only mod that is somewhat modying something about trains is LTN but that dont do anything with signals only with train stations

**Comment by Sopel97** [comment]
Fixed by commits 61ba57df22043e855c62db69909f7dd5b5e960af and c2000a77fc919b98ae3aee9961c2c5b84d4444a0 (version 1.1.1). This rail network is crazy, and there's a lot of weird things going on. (The mod also identified plenty of issues :))

The way this railway network is made causes a lot of exploration to get enough rails in the graph. This makes the update take a few seconds (!). Makes it also a good test-case for potential optimization. Al;so makes me think that a non-realtime (single use) annotation (through some button) could be useful for such large and interconnected networks. For now I suggest using /editor and pause.

 Very nice test case for the mod overall, I'll be using it a lot. Thank you for reporting this.
